baseURL = 'https://withmetta.pali.tools/'
languageCode = 'en-us'
title = 'With Metta'
theme = "ananke"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Share your stories of loving-kindness."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  recent_posts_number = 30

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
